/**
 * Created by Sherlock on 02.05.2022.
 */

export const YATT_TAX_INFO_UPDATE_STATE = "YATT_TAX_INFO_UPDATE_STATE";
export const YUR_TAX_INFO_UPDATE_STATE = "YUR_TAX_INFO_UPDATE_STATE";
export const PHYSIC_TAX_INFO_UPDATE_STATE = "PHYSIC_TAX_INFO_UPDATE_STATE";
export const GLOBAL_UPDATE_STATE = "GLOBAL_UPDATE_STATE";
export const RENT_UPDATE_STATE = "RENT_UPDATE_STATE";
